In [1]:
import numpy as np

Creating array from list


In [2]:
arr_1d = np.array([1,2,3,4,5 ])
print("1D Array:\n", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)



1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
import time 

start = time.time()
py_list = [i*2 for i in range(1000000)]
end = time.time()
print("Time taken with Python list:", end - start)

start = time.time()
np_array = np.array([i*2 for i in range(1000000)])
end = time.time()
print("Time taken with NumPy array:", end - start)


Time taken with Python list: 0.483964204788208
Time taken with NumPy array: 1.3089196681976318


In [4]:
'''
Time taken with Python list: 0.123456 seconds
Time taken with NumPy array: 0.045678 seconds
# The NumPy array is significantly faster for large data operations compared to a Python list.
'''

'\nTime taken with Python list: 0.123456 seconds\nTime taken with NumPy array: 0.045678 seconds\n# The NumPy array is significantly faster for large data operations compared to a Python list.\n'

Creating metrics from scratch


In [5]:
zeros = np.zeros((2,2))
print("Zeros Array:\n", zeros)

ones = np.ones((2,2))
print("Ones Array:\n", ones)

full = np.full((2,2),8)
print("Full Array:\n", full)

random_array = np.random.random((2,2))
print("Random Array:\n", random_array)

identity = np.identity(3)
print("Identity Matrix:\n", identity)

sequence = np.arange(1,20,3)
print("sequence Matrix:\n",sequence)

Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]]
Full Array:
 [[8 8]
 [8 8]]
Random Array:
 [[0.74848384 0.12373434]
 [0.43922464 0.0342635 ]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
sequence Matrix:
 [ 1  4  7 10 13 16 19]


Vector, Metrics and Tensor


In [6]:
vector = np.array([1,2,3])
print("Vector:\n", vector)

Metrics = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print("Metrics Array:\n", Metrics) 

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor Array:\n", tensor)

Vector:
 [1 2 3]
Metrics Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6.2]])

print("Shape of arr:", arr.shape)
print("Number of dimensions of arr:", arr.ndim)
print("Size of arr:", arr.size)
print("Data type of arr:", arr.dtype)
print("Item size of arr:", arr.itemsize)


Shape of arr: (2, 3)
Number of dimensions of arr: 2
Size of arr: 6
Data type of arr: float64
Item size of arr: 8


Array Reshaping


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n", arr)

arr_transpose = arr.T
print("Transposed Array:\n", arr_transpose)

Reshaped_array = arr.reshape(3, 2)
print("Reshaped Array:\n", Reshaped_array)

flattened_array = Reshaped_array.flatten()
print("Flattened Array:\n", flattened_array)

Raveled_array = Reshaped_array.ravel()
print("Raveled Array:\n", Raveled_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened Array:
 [1 2 3 4 5 6]
Raveled Array:
 [1 2 3 4 5 6]


Numpy Array Operation


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing : \n", arr[2:7])
print("With Step Slicing : \n", arr[2:7:2])
print("Reverse Slicing : \n", arr[::-1])
print("Slicing with Negative Indices : \n", arr[-5:-1])
print("Slicing with Step and Negative Indices : \n", arr[-1:-6:-2])


Basic Slicing : 
 [3 4 5 6 7]
With Step Slicing : 
 [3 5 7]
Reverse Slicing : 
 [10  9  8  7  6  5  4  3  2  1]
Slicing with Negative Indices : 
 [6 7 8 9]
Slicing with Step and Negative Indices : 
 [10  8  6]


In [10]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
print("Specific Element Slicing:\n", array_2d[1, 2])  # Accessing element at row 1, column 2
print("Row Slicing:\n", array_2d[1, :])  # Accessing entire row 1
print("Column Slicing:\n", array_2d[:, 1])  # Accessing entire column 1
print("Sub-array Slicing:\n", array_2d[0:2, 1:3])  # Accessing a sub-array from rows 0 to 1 and columns 1 to 2


Specific Element Slicing:
 6
Row Slicing:
 [4 5 6]
Column Slicing:
 [2 5 8]
Sub-array Slicing:
 [[2 3]
 [5 6]]


### Sorting


In [11]:
unsorted_array = np.array([3, 1, 4, 2, 5])
print(np.sort(unsorted_array))  # Sorts the array in ascending order

sorted_indices = np.argsort(unsorted_array)
print("Sorted indices:", sorted_indices)  # Returns the indices that would sort the array


[1 2 3 4 5]
Sorted indices: [1 3 0 2 4]


Filter


In [12]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers %  2 == 0]
print("Even Numbers:\n", even_number)

odd_number = numbers[numbers % 2 != 0]
print("Odd Numbers:\n", odd_number)

Even Numbers:
 [ 2  4  6  8 10]
Odd Numbers:
 [1 3 5 7 9]


Filtering with mask


In [13]:
mask = (numbers > 5) & (numbers < 9)
filtered_numbers = numbers[mask]
print("Filtered Numbers (5 < x < 9):\n", filtered_numbers)

Filtered Numbers (5 < x < 9):
 [6 7 8]


Fancy Indexing vs np.where()


In [14]:
indices = [0, 2, 4, 6, 8]
print("Elements at Indices 0, 2, 4, 6, 8:\n", numbers[indices])

where_indices = np.where(numbers > 5)
print("Indices where numbers > 5:\n", numbers[where_indices])  # Returns the indices of elements greater than 5

Elements at Indices 0, 2, 4, 6, 8:
 [1 3 5 7 9]
Indices where numbers > 5:
 [ 6  7  8  9 10]


In [15]:
conditional_array = np.where(numbers > 5, numbers / 3, numbers * 2)
print("Conditional Array (numbers > 5 ? numbers / 3 : numbers * 2):\n", conditional_array)

Conditional Array (numbers > 5 ? numbers / 3 : numbers * 2):
 [ 2.          4.          6.          8.         10.          2.
  2.33333333  2.66666667  3.          3.33333333]


Adding or removing array

In [16]:
arr1 =np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_sum = arr1 + arr2
print("Sum of arr1 and arr2:\n", arr_sum) 

combined = np.concatenate((arr1, arr2))
print("Concatenated Array:\n", combined)

Sum of arr1 and arr2:
 [5 7 9]
Concatenated Array:
 [1 2 3 4 5 6]


Array compatibility

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])

print("compatibility shape of a, b, c:",a.shape == b.shape == c.shape) 

compatibility shape of a, b, c: True


In [19]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Original Array:\n", original)
print("New Row to Add:\n", new_row)
print("Array after adding new row:\n", with_new_row)


new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("New Column to Add:\n", with_new_col)

Original Array:
 [[1 2]
 [3 4]]
New Row to Add:
 [[5 6]]
Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
New Column to Add:
 [[1 2 7]
 [3 4 8]]


In [23]:
arr = np.array([[1, 2,3, 4]])

deleted = np.delete(arr,2, axis=1) # Deleting the second column
print("Original Array:\n", arr)
print("Array after deleting second column:\n", deleted) 

Original Array:
 [[1 2 3 4]]
Array after deleting second column:
 [[1 2 4]]
